name: Build bcc-application images

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        bcc-version: ["0.29.0", "v0.28.0", "v0.27.0", "v0.26.0", "v0.25.0"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        build-args: |
          BCC_VERSION=${{ matrix.bcc-version }}
        context: .
        file: ./docker/Dockerfile.bcc-application
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-bcc-application:${{ matrix.bcc-version }}
