name: Build bpftrace images self-hosted

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        bpftrace-version: ["v0.19.0"]

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        build-args: |
          BPFTRACE_VERSION=${{ matrix.bpftrace-version }}
        context: .
        file: ./docker/Dockerfile.bpftrace
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-bpftrace:${{ matrix.bpftrace-version }}
