name: Upload Python Package and Build Image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        build-args: |
          BCC_VERSION=0.28.0
        context: .
        file: ./docker/Dockerfile.bcc
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-bcc:v0.28.0
